solr:
  url: http://localhost:8983/solr/argo

argo:
  url: https://argo.stanford.edu

google_books_apo: 'druid:bf569gy6501'

dor_services:
  url: "http://localhost:3003"
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4

feature_flags:
  bulk_actions: false